version: '3.8'

services:
  php:
    build: ./docker/php
    container_name: distriforce-php-prod
    restart: always
    volumes:
      - ./src:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - distriforce-network

  nginx:
    image: nginx:alpine
    container_name: distriforce-nginx-prod
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - distriforce-network

  mysql:
    image: mysql:8.0
    container_name: distriforce-mysql-prod
    restart: always
    environment:
      MYSQL_DATABASE: distriforce_ai
      MYSQL_ROOT_PASSWORD: 8_Z04?G%WjvwX{pgu9UKArW5~%nzrn
      MYSQL_USER: xavier
      MYSQL_PASSWORD: 8_Z04?G%WjvwX{pgu9UKArW5~%nzrn
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - distriforce-network

networks:
  distriforce-network:
    driver: bridge

volumes:
  mysql_data: